-- Deploy providers
-- requires: pgque
--
-- Provider accounts — one row per practitioner using this Calendry instance.
-- v0.1 is single-org per deploy; provider_id foreign keys in other tables
-- allow a two-therapist practice sharing one instance (see SPEC §Boundaries).
--
-- oauth_status values: 'connected' | 'degraded' | 'revoked'
-- The worker pauses google_push for providers in 'degraded'/'revoked' states.

begin;

create table if not exists providers (
  id                         uuid        not null default gen_random_uuid(),
  slug                       text        not null,
  email                      text        not null,
  home_tz                    text        not null,
  google_oauth_refresh_token text,
  oauth_status               text        not null default 'connected'
                               check (oauth_status in ('connected', 'degraded', 'revoked')),
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now(),

  constraint providers_pkey primary key (id),
  constraint providers_slug_uq unique (slug),
  constraint providers_email_uq unique (email)
);

comment on table  providers                            is 'Service provider accounts — one row per practitioner.';
comment on column providers.id                         is 'UUID primary key, generated by gen_random_uuid().';
comment on column providers.slug                       is 'URL-safe identifier used in /book/{slug} routes.';
comment on column providers.email                      is 'Provider email; also the admin login identity for magic link.';
comment on column providers.home_tz                    is 'IANA timezone string (e.g. America/Los_Angeles). All availability rules are expressed in this zone.';
comment on column providers.google_oauth_refresh_token is 'Encrypted Google OAuth refresh token. Null until provider connects Google Calendar.';
comment on column providers.oauth_status               is 'Google OAuth connection health: connected | degraded | revoked.';
comment on column providers.created_at                 is 'Row creation timestamp (UTC).';
comment on column providers.updated_at                 is 'Row last-update timestamp (UTC). Updated by application on every write.';

commit;
